### ISSUE TITLE
关于修改代码生成路径后生成的文件报错的问题

### ISSUE THREAD

**Issue by yanwencaihubei** [baomidou/mybatis-plus-samples#17]
修改了下面的路径后
//        gc.setOutputDir(projectPath + "/mybatis-plus-sample-generator/src/main/java");
生成的实体类报错

import com.baomidou.mybatisplus.samples.generator.common.BaseController;
这个包丢失

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues
