### ISSUE TITLE
大佬包更新不下来啊，

### ISSUE THREAD

**Issue by lexingrensheng** [baomidou/mybatis-plus-samples#27]
http\://repo.maven.apache.org/maven2/.error=
http\://gnet-central.quanshi.com\:9001/nexus/content/groups/public/.lastUpdated=1575281831752
http\://maven.aliyun.com/nexus/content/groups/public/.error=Could not transfer artifact com.baomidou\:mybatis-plus\:pom\:3.2.1 from/to aliyun_1 (http\://maven.aliyun.com/nexus/content/groups/public/)\: java.lang.RuntimeException\: Unexpected error\: java.security.InvalidAlgorithmParameterException\: the trustAnchors parameter must be non-empty

我已经不清楚现在到底用那个版本了，那个版本更新下来都是好多错

**Comment by nieqiurong** [comment]
例子里面似乎没有使用过3.2.1，而是使用的快照版本，正式的版本用3.3.0.

**Comment by watermelon-tech** [comment]
？？？？？？？？？？？？？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nieqiuqiu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 上午10:09
收件人:&nbsp;"baomidou/mybatis-plus-samples"<mybatis-plus-samples@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus-samples] 大佬包更新不下来啊， (#27)




例子里面似乎没有使用过3.2.1，而是使用的快照版本，正式的版本用3.3.0.
