### ISSUE TITLE
关于MP+Springboot service层方法互相调用会循环引用的解决方法探索

### ISSUE THREAD

**Issue by CzyerChen** [baomidou/mybatis-plus-samples#28]
1.场景：
```java
class AServiceImpl extends ServiceImpl<AMapper, A> implements IAService{

//一个findByName比较通用的自定义方法

LambdaQueryWrapper<A> wrapper = new LambdaQueryWrapper<>();
wrapper.eq(A::getName,name);
return baseMapper.selectOne(wrapper);

}
```

2.问题：

class B serviceImp类中需要调用A的findByName，
然后A serviceImpl类中也有方法需要调用B中的方法，
那么就会存在循环引用，类似这种类型的case，一般可以怎么调整代码结构解除循环引用？

3. 注意：
通过传统的mybatis的方法能够将类似findByName的基础方法下放到mapper实现可以解决以上问题，但是仍想保留mybatis plus的特性的话，并不想每次通过AMapper.selectOne(new QueryWrapper().eq(A::getName))，那样就缺乏了通用性，
应该如何调整代码结构，谢谢！

**Comment by qmdx** [comment]
就算你所有方法在 mapper 一样存在循环调用，这个还是通过编码规范来规避。service 理论上方法只有两种 = 业务单元 + CRUD操作 ， A 业务单元调用对方 B service 应该是只能调用 CRUD 基本操作 补能调用业务单元，这样就不存在互相调用问题

**Comment by CzyerChen** [comment]
Thanks!
