### ISSUE TITLE
DM数据库测试未通过

### ISSUE THREAD

**Issue by philhong2012** [baomidou/mybatis-plus-samples#30]
测试步骤如下：
运行mysqlgenerator类main 方法
输入模块名
输入表名

结果：
报有歧义的列名[TABLE_NAME]错误。

**Comment by zhaowenzhe** [comment]
同样的问题

**Comment by qmdx** [comment]
是达梦库？ 你应该参考 orace 的方式，如果还不行看下怎么自定义处理

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/2102
