### ISSUE TITLE
typehandler的使用

### ISSUE THREAD

**Issue by HaiBinSu** [baomidou/mybatis-plus-samples#38]
![image](https://user-images.githubusercontent.com/3581889/82998869-d4fb2e80-a03a-11ea-973f-6bc3863108cc.png)
![image](https://user-images.githubusercontent.com/3581889/82998898-e04e5a00-a03a-11ea-9d51-ac0998ca5794.png)
![image](https://user-images.githubusercontent.com/3581889/82999023-096eea80-a03b-11ea-8fe4-8444674dc296.png)
在我的TableName和TableField注解中，autoResultMap和typeHandler都是报错的，这是为什么呢，mybatisplus版本为3.1.0，在springboot项目中

**Comment by qmdx** [comment]
请使用最新版本 3.3.2 试试，不维护低版本
