### ISSUE TITLE
maven依赖导入报错，Cannot resolve com.baomidou:mybatis-plus-generator:3.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by mrzhiyi** [baomidou/mybatis-plus-samples#47]
Cannot resolve com.baomidou:mybatis-plus-generator:3.5.0-SNAPSHOT
依赖的是 com.baomidou:mybatis-plus-generator:3.5.0-SNAPSHOT，但是在maven的中央仓库中未找到此版本
![image](https://user-images.githubusercontent.com/31000822/104844234-039b8180-590a-11eb-95da-269e32127498.png)

**Comment by gitforcoding** [comment]
实测修改为3.3.0可用
`<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.0</version>
        </dependency>`

**Comment by qmdx** [comment]
快照版本
