### ISSUE TITLE
maven依赖仓库并没有官网上的3.4.2版本，导致依赖出错，麻烦更新一下啊

### ISSUE THREAD

**Issue by PopsiCola** [baomidou/mybatis-plus-samples#49]
![image](https://user-images.githubusercontent.com/50124380/106247966-4420c680-624b-11eb-8804-d58d0de0dc5e.png)
![image](https://user-images.githubusercontent.com/50124380/106247971-471bb700-624b-11eb-852d-e1d75c5f19bc.png)

**Comment by PopsiCola** [comment]
说错了 是代码生成器没有 3.4.2 mybatis-plus-generator

**Comment by qmdx** [comment]
3.4.1 以后版本不会再有 generator 会独立开发
