### ISSUE TITLE
Where is the mybatis-plus-generator for 3.5.0-SNAPSHOT？

### ISSUE THREAD

**Issue by shibenxia** [baomidou/mybatis-plus-samples#55]
I download the project,but has error.Means don't find the mybatis-plus-generator for 3.5.0-SNAPSHOT.

**Comment by qmdx** [comment]
https://search.maven.org/search?q=a:mybatis-plus-generator

**Comment by shibenxia** [comment]
It's the 3.5.0,not 3.5.0-SNAPSHOT for the require.
