### ISSUE TITLE
Where is sample for combination condition like AND/OR?

### ISSUE THREAD

**Issue by trungdoviet** [baomidou/mybatis-plus-samples#73]
Hi team
i have requirement to write SQL like:
```sql
Select * from table_a where col1 IN (1,2,3) OR col2 IN ("x", "y", "z")
```

How to write this one with mybatis-plus?

**Comment by qiuzhihui1990** [comment]
Hello.
I think you can try the following:

`in("col1", collect1).or().in("col2",collect2)`
