### ISSUE TITLE
如何自定义生成主键啊?

### ISSUE THREAD

**Issue by liuboren0617** [baomidou/mybatis-plus-samples#9]
3.正常配置GlobalConfiguration.keyGenerator
@Bean
public GlobalConfiguration globalConfiguration() {
    GlobalConfiguration conf = new GlobalConfiguration();
    conf.setKeyGenerator(new OracleKeyGenerator());
    return conf;
}
请问官网的这步骤在哪配置?,   这个GlobalConfiguration类找不到啊

这是我的依赖

  <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>

**Comment by cthv5** [comment]
same problem

**Comment by mylifeonmars** [comment]
不声明@TableId
或者如下
@TableId(type = IdType.NONE)
@TableId(type = IdType.INPUT)
直接setId即可

**Comment by qmdx** [comment]
UP
